# Generated by Django 4.2.7 on 2023-11-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vis", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="totalcases",
            name="total_cases_uf_year",
        ),
        migrations.RemoveConstraint(
            model_name="totalcases100khab",
            name="total_cases_100k_hab_uf_year",
        ),
        migrations.AddField(
            model_name="totalcases",
            name="disease",
            field=models.CharField(
                choices=[
                    ("dengue", "Dengue"),
                    ("chik", "Chigungunya"),
                    ("zika", "Zika"),
                ],
                default="dengue",
            ),
        ),
        migrations.AddField(
            model_name="totalcases100khab",
            name="disease",
            field=models.CharField(
                choices=[
                    ("dengue", "Dengue"),
                    ("chik", "Chigungunya"),
                    ("zika", "Zika"),
                ],
                default="dengue",
            ),
        ),
        migrations.AddConstraint(
            model_name="totalcases",
            constraint=models.UniqueConstraint(
                fields=("uf", "year", "disease"), name="unique_total_cases"
            ),
        ),
        migrations.AddConstraint(
            model_name="totalcases100khab",
            constraint=models.UniqueConstraint(
                fields=("uf", "year", "disease"),
                name="unique_total_cases_100k_hab",
            ),
        ),
    ]
