# Generated by Django 4.2.7 on 2023-11-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vis", "0002_remove_totalcases_total_cases_uf_year_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="totalcases100khab",
            name="total_cases",
            field=models.FloatField(),
        ),
    ]
