# Generated by Django 4.2.11 on 2024-03-07 21:11

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("vis", "0004_alter_totalcases_year_alter_totalcases100khab_year"),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "geocode",
                    models.CharField(
                        max_length=7,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField()),
            ],
            options={
                "db_table": "brasil_cities",
            },
        ),
        migrations.CreateModel(
            name="GeoMacroSaude",
            fields=[
                (
                    "geocode",
                    models.CharField(
                        max_length=4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        srid=4326
                    ),
                ),
            ],
            options={
                "db_table": "geo_brasil_macro_saude",
            },
        ),
        migrations.CreateModel(
            name="Macroregion",
            fields=[
                (
                    "geocode",
                    models.CharField(
                        max_length=1,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField()),
            ],
            options={
                "db_table": "brasil_macroregions",
            },
        ),
        migrations.CreateModel(
            name="Mesoregion",
            fields=[
                (
                    "geocode",
                    models.CharField(
                        max_length=4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField()),
            ],
            options={
                "db_table": "brasil_mesoregions",
            },
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "geocode",
                    models.CharField(
                        max_length=2,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField()),
                ("uf", models.CharField(max_length=2)),
                (
                    "macroregion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="vis.macroregion",
                    ),
                ),
            ],
            options={
                "db_table": "brasil_states",
            },
        ),
        migrations.CreateModel(
            name="ResultsProbLSTM",
            fields=[
                (
                    "date",
                    models.DateField(
                        db_column="date", primary_key=True, serialize=False
                    ),
                ),
                ("lower_2_5", models.FloatField()),
                ("lower_25", models.FloatField()),
                ("forecast", models.FloatField()),
                ("upper_75", models.FloatField()),
                ("upper_97_5", models.FloatField()),
                ("prob_high", models.FloatField()),
                ("prob_low", models.FloatField()),
                ("HT", models.FloatField()),
                ("LT", models.FloatField()),
                ("HTinc", models.FloatField()),
                ("LTinc", models.FloatField()),
                (
                    "macroregion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="vis.geomacrosaude",
                    ),
                ),
            ],
            options={
                "db_table": "results_prob_lstm",
            },
        ),
        migrations.CreateModel(
            name="Microregion",
            fields=[
                (
                    "geocode",
                    models.CharField(
                        max_length=5,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField()),
                (
                    "mesoregion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="vis.mesoregion",
                    ),
                ),
            ],
            options={
                "db_table": "brasil_microregions",
            },
        ),
        migrations.AddField(
            model_name="mesoregion",
            name="state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="vis.state"
            ),
        ),
        migrations.CreateModel(
            name="GeoState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        srid=4326
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="vis.state",
                    ),
                ),
            ],
            options={
                "db_table": "geo_brasil_states",
            },
        ),
        migrations.CreateModel(
            name="GeoMicroregion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        srid=4326
                    ),
                ),
                (
                    "microregion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="vis.microregion",
                    ),
                ),
            ],
            options={
                "db_table": "geo_brasil_microregions",
            },
        ),
        migrations.CreateModel(
            name="GeoMesoregion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        srid=4326
                    ),
                ),
                (
                    "mesoregion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="vis.mesoregion",
                    ),
                ),
            ],
            options={
                "db_table": "geo_brasil_mesoregions",
            },
        ),
        migrations.AddField(
            model_name="geomacrosaude",
            name="state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="vis.state"
            ),
        ),
        migrations.CreateModel(
            name="GeoMacroregion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        srid=4326
                    ),
                ),
                (
                    "macroregion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="vis.macroregion",
                    ),
                ),
            ],
            options={
                "db_table": "geo_brasil_macroregions",
            },
        ),
        migrations.CreateModel(
            name="GeoCity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        srid=4326
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="vis.city",
                    ),
                ),
            ],
            options={
                "db_table": "geo_brasil_cities",
            },
        ),
        migrations.AddField(
            model_name="city",
            name="microregion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="vis.microregion",
            ),
        ),
        migrations.AddConstraint(
            model_name="resultsproblstm",
            constraint=models.UniqueConstraint(
                fields=("date", "macroregion"), name="results_prob_lstm_unique"
            ),
        ),
    ]
