# Generated by Django 4.2.5 on 2024-03-08 20:59

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vis", "0006_populate_geo_brasil_tables"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geocity",
            name="geometry",
            field=django.contrib.gis.db.models.fields.GeometryField(srid=4326),
        ),
        migrations.AlterField(
            model_name="geomacroregion",
            name="geometry",
            field=django.contrib.gis.db.models.fields.GeometryField(srid=4326),
        ),
        migrations.AlterField(
            model_name="geomacrosaude",
            name="geometry",
            field=django.contrib.gis.db.models.fields.GeometryField(srid=4326),
        ),
        migrations.AlterField(
            model_name="geomesoregion",
            name="geometry",
            field=django.contrib.gis.db.models.fields.GeometryField(srid=4326),
        ),
        migrations.AlterField(
            model_name="geomicroregion",
            name="geometry",
            field=django.contrib.gis.db.models.fields.GeometryField(srid=4326),
        ),
        migrations.AlterField(
            model_name="geostate",
            name="geometry",
            field=django.contrib.gis.db.models.fields.GeometryField(srid=4326),
        ),
    ]
