# Generated by Django 4.2.5 on 2024-03-11 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("vis", "0008_populate_geo_macro_saude_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResultsProbForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_column="date")),
                ("lower_2_5", models.FloatField()),
                ("lower_25", models.FloatField()),
                ("forecast", models.FloatField()),
                ("upper_97_5", models.FloatField()),
                ("upper_75", models.FloatField()),
                ("prob_high", models.FloatField()),
                ("prob_low", models.FloatField()),
                ("HT", models.FloatField()),
                ("LT", models.FloatField()),
                ("HTinc", models.FloatField()),
                ("LTinc", models.FloatField()),
                (
                    "geocode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="vis.geomacrosaude",
                    ),
                ),
            ],
            options={
                "db_table": "results_prob_forecast",
            },
        ),
        migrations.DeleteModel(
            name="ResultsProbLSTM",
        ),
        migrations.AddConstraint(
            model_name="resultsprobforecast",
            constraint=models.UniqueConstraint(
                fields=("date", "geocode"), name="results_prob_forecast_unique"
            ),
        ),
    ]
