# Generated by Django 4.2.5 on 2024-03-11 16:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vis", "0009_resultsprobforecast_delete_resultsproblstm_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resultsprobforecast",
            old_name="HT",
            new_name="high_incidence_threshold",
        ),
        migrations.RenameField(
            model_name="resultsprobforecast",
            old_name="HTinc",
            new_name="high_threshold",
        ),
        migrations.RenameField(
            model_name="resultsprobforecast",
            old_name="LT",
            new_name="low_incidence_threshold",
        ),
        migrations.RenameField(
            model_name="resultsprobforecast",
            old_name="LTinc",
            new_name="low_threshold",
        ),
    ]
