# Generated by Django 4.2.20 on 2025-04-22 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("vis", "0015_alter_totalcases_year_alter_totalcases100khab_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="macro_health",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cities",
                to="vis.geomacrosaude",
            ),
        ),
    ]
