# Generated by Django 4.2.23 on 2026-01-03 12:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vis", "0017_populate_city_macro_health"),
    ]

    operations = [
        migrations.AlterField(
            model_name="totalcases",
            name="year",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1980),
                    django.core.validators.MaxValueValidator(2026),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="totalcases100khab",
            name="year",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1980),
                    django.core.validators.MaxValueValidator(2026),
                ]
            ),
        ),
    ]
