services:
  frontend:
    environment:
        NODE_ENV: development
    volumes:
      - ../frontend:/opt/services/mosqlimate
    networks:
      - infodengue-dev_infodengue

  backend:
    command: poetry run python manage.py runserver 0.0.0.0:${BACKEND_PORT}
    volumes:
      - ../backend:/opt/services/mosqlimate
    networks:
      - infodengue-dev_infodengue

  worker:
    volumes:
      - ../backend:/opt/services/mosqlimate
    networks:
      - infodengue-dev_infodengue

networks:
  infodengue-dev_infodengue:
    external: true
