services:
  frontend:
    environment:
        NODE_ENV: production
    networks:
      - infodengue-prod_infodengue

  backend:
    command: poetry run gunicorn -w 4 -b 0.0.0.0:${BACKEND_PORT} -k uvicorn.workers.UvicornWorker mosqlimate.asgi:application --limit-request-line 8188 --log-file -
    networks:
      - infodengue-prod_infodengue

  worker:
    networks:
      - infodengue-prod_infodengue

networks:
  infodengue-prod_infodengue:
    external: true
