version: 1.8.0
compose-app: docker-compose
env-file: .env
defaults:
  group: {{ env.ENV }}
service-groups:
  - name: prod
    project-name: mosqlimate
    compose-path: 
      - containers/compose.yaml
      - containers/compose-prod.yaml
    env-file: .env
    services:
      default: django,postgres,nginx
      available:
        - name: django
        - name: postgres
        - name: nginx

  - name: dev
    project-name: mosqlimate
    compose-path:
      - containers/compose.yaml
      - containers/compose-dev.yaml
    env-file: .env
    services:
      default: django,postgres
      available:
        - name: django
        - name: postgres
