version: 1.8.1

groups:

  docker:
    env-file: .env
    targets:
      build:
        help: Build containers
        run: |
          sugar build --group $ENV

      start:
        help: Start all containers
        run: |
          sugar up --group $ENV --options "--no-start"
          sugar start --group $ENV

      stop:
        help: Start all containers
        run: |
          sugar stop --group $ENV

  django:
    targets:
      createsuperuser:
        args:
          email:
            help: Specify the email
            type: string
            required: True
          username:
            help: Specify the username
            type: string
            required: True
          password:
            help: Specify the password
            type: string
            required: True
        help: Run `createsuperuser` inside container
        run: |
          sugar run --service django --cmd "python manage.py createsuperuser \
            --noinput --username {{ args.username }} --email {{ args.email }}"

      changepassword:
        args:
          username:
            help: Specify the username
            type: string
            required: True
        help: Run `changepassword <user>` inside container
        run: |
          sugar run --service django --cmd "python manage.py changepassword {{ args.username }}"

      migrate:
        help: Run `migrate` inside container
        env-file: .env
        run: |
          sugar run --service django --cmd "python manage.py migrate --no-input"

      collectstatic:
        help: Run `collectstatic` inside container
        run: |
          sugar run --service django --cmd "python manage.py collectstatic --no-input"

      shell:
        help: Enters in Django Shell on container
        run: |
          sugar run --service django --cmd "python manage.py shell"

      dbshell:
        help: Enters in Django Database shell on container
        run: |
          sugar run --service django --cmd "python manage.py dbshell"


  dev:
    targets:
      dotenv:
        help: Configure .env file
        run: |
          python contrib/scripts/do_dotenv.py

      psql-conf:
        help: Configure postgresq.conf file
        run: |
          python contrib/scripts/do_psqlconf.py
