version: 1.8.0
compose-app: docker-compose
env-file: .env
defaults:
  group: {{ env.ENV }}
groups:
  prod:
    project-name: mosqlimate
    compose-path: 
      - containers/compose.yaml
      - containers/compose-prod.yaml
    env-file: .env
    environment:
        NODE_ENV: "production webpack --progress --bail --mode=production"
    services:
      default: django,worker,postgres,documentation,redis
      available:
        - name: django
        - name: worker
        - name: postgres
        - name: documentation
        - name: redis

  dev:
    project-name: mosqlimate
    compose-path:
      - containers/compose.yaml
      - containers/compose-dev.yaml
    env-file: .env
    services:
      default: django,worker,postgres,documentation,redis
      available:
        - name: django
        - name: worker
        - name: postgres
        - name: documentation
        - name: redis
