backend: compose
env-file: .env

defaults:
  profile: "${{ env.ENV }}"
  project-name: "mosqlimate-${{ env.VERSION }}"

profiles:
  dev:
    env-file: .env
    config-path:
      - containers/compose.yaml
      - containers/compose-dev.yaml
    services:
      available:
        - name: frontend
        - name: backend
        - name: worker
        - name: postgres
        - name: documentation
        - name: redis
        - name: ollama

  prod:
    env-file: .env
    config-path:
      - containers/compose.yaml
      - containers/compose-prod.yaml
    services:
      available:
        - name: frontend
        - name: backend
        - name: worker
        - name: postgres
        - name: documentation
        - name: redis
        - name: ollama
