version: 1.8.0
compose-app: docker-compose
env-file: .env
defaults:
  group: {{ env.ENV }}
groups:
  prod:
    project-name: mosqlimate
    compose-path:
      - contrib/compose.yaml
      - contrib/compose-prod.yaml
    env-file: .env
    services:
      default: frontend,backend,worker,postgres,documentation,redis
      available:
        - name: frontend
        - name: backend
        - name: worker
        - name: postgres
        - name: documentation
        - name: redis

  dev:
    project-name: mosqlimate
    compose-path:
      - contrib/compose.yaml
      - contrib/compose-dev.yaml
    env-file: .env
    services:
      default: frontend,backend,worker,postgres,documentation,redis
      available:
        - name: frontend
        - name: backend
        - name: worker
        - name: postgres
        - name: documentation
        - name: redis
