services:
  frontend:
    build:
      target: deps
    environment:
      NODE_ENV: development
      WATCHPACK_POLLING: "true"
      FRONTEND_PORT: ${FRONTEND_PORT}
    command: npm run dev
    volumes:
      - ./frontend/:/app
      - /app/node_modules
      - /app/.next

  backend:
    command: python manage.py runserver 0.0.0.0:${BACKEND_PORT}
    volumes:
      - ./backend/:/opt/services/mosqlimate
      - backend_data:/opt/services/storage

  worker:
    volumes:
      - backend_data:/opt/services/storage

volumes:
  backend_data:

networks:
  infodengue:
    name: ${INFODENGUE_NETWORK_NAME:-infodengue-dev_infodengue}
