services:
  frontend:
    hostname: mosqlimate-${VERSION}-frontend
    build:
      context: .
      dockerfile: containers/frontend/Dockerfile
      args:
        - UID=${HOST_UID}
        - GID=${HOST_GID}
        - PORT=${FRONTEND_PORT}
        - NEXT_PUBLIC_BACKEND_URL=${BACKEND_URL}
        - NEXT_PUBLIC_DOCS_URL=${DOCS_URL}
        - BACKEND_PORT=${BACKEND_PORT}
    environment:
      NODE_ENV: production
      PORT: ${FRONTEND_PORT}
      BACKEND_PORT: ${BACKEND_PORT}
      NEXT_PUBLIC_FRONTEND_URL: ${FRONTEND_URL}
      NEXT_PUBLIC_BACKEND_URL: ${BACKEND_URL}
      NEXT_PUBLIC_DOCS_URL: ${DOCS_URL}
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    user: "mosqlimate:mosqlimate"
    restart: unless-stopped
    command: node server.js
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:${FRONTEND_PORT}"]
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 40s
    volumes:
      - /opt/services/Mosqlimate/storage/django/media:/app/public/media
    networks:
      - default

  backend:
    hostname: mosqlimate-${VERSION}-backend
    environment:
      RUN_MIGRATE: ${CI}
      PYTHONUNBUFFERED: 1
      ADMIN_UIDKEY: ${ADMIN_UIDKEY}
      FRONTEND_SECRET: ${FRONTEND_SECRET}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      SECRET_KEY: ${SECRET_KEY}
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}
      DJANGO_LOG_LEVEL: ${DJANGO_LOG_LEVEL}
      ENV: ${ENV}
      VERSION: ${VERSION}
      CI: ${CI}
      BACKEND_PORT: ${BACKEND_PORT}
      BACKEND_URL: ${BACKEND_URL}
      FRONTEND_PORT: ${FRONTEND_PORT}
      FRONTEND_URL: ${FRONTEND_URL}
      MKDOCS_PORT: ${MKDOCS_PORT}
      REDIS_PORT: ${REDIS_PORT}
      DOCS_URL: ${DOCS_URL}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_SECRET: ${GITHUB_SECRET}
      GITHUB_APP: ${GITHUB_APP}
      GITHUB_APP_ID: ${GITHUB_APP_ID}
      GITHUB_PRIVATE_KEY: ${GITHUB_PRIVATE_KEY}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_SECRET: ${GOOGLE_SECRET}
      GITLAB_CLIENT_ID: ${GITLAB_CLIENT_ID}
      GITLAB_SECRET: ${GITLAB_SECRET}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DEFAULT_POSTGRES_URI: ${DEFAULT_POSTGRES_URI}
      INFODENGUE_POSTGRES_URI: ${INFODENGUE_POSTGRES_URI}
      SENTRY_DSN: ${SENTRY_DSN}
      DEFAULT_FROM_EMAIL: ${DEFAULT_FROM_EMAIL}
      EMAIL_BACKEND: ${EMAIL_BACKEND}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
      EMAIL_USE_TLS: ${EMAIL_USE_TLS}
      BACKEND_HOST_DATA_PATH: ${BACKEND_HOST_DATA_PATH}
      BACKEND_CONTAINER_DATA_PATH: ${BACKEND_CONTAINER_DATA_PATH}
      EPISCANNER_HOST_DATA_DIR: ${EPISCANNER_HOST_DATA_DIR}
      BACKUP_DIR_HOST: ${BACKUP_DIR_HOST}
      MOSQLIENT_API_URL: ${MOSQLIENT_API_URL}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      YOUTUBE_API_KEY: ${YOUTUBE_API_KEY}
      EPIDBOT_API_KEY: ${EPIDBOT_API_KEY}
    build:
      context: .
      dockerfile: containers/mosqlimate/Dockerfile
      args:
        - UID=${HOST_UID}
        - GID=${HOST_GID}
        - BACKEND_CONTAINER_DATA_PATH=${BACKEND_CONTAINER_DATA_PATH}
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    user: "mosqlimate:mosqlimate"
    volumes:
      - /home/administrador/episcanner:/opt/services/storage/django/episcanner
      - /opt/services/Mosqlimate/storage/django:/opt/services/storage/django
      - /Storage/backups/mosqlimate:/opt/backups
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:${BACKEND_PORT}/api/status/"]
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 40s
    depends_on:
      postgres:
        condition: service_healthy
    command: daphne -b 0.0.0.0 -p ${BACKEND_PORT} mosqlimate.asgi:application
    networks:
      - default
      - infodengue

  worker:
    hostname: mosqlimate-${VERSION}-worker
    restart: unless-stopped
    environment:
      ADMIN_UIDKEY: ${ADMIN_UIDKEY}
      FRONTEND_SECRET: ${FRONTEND_SECRET}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      SECRET_KEY: ${SECRET_KEY}
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}
      DJANGO_LOG_LEVEL: ${DJANGO_LOG_LEVEL}
      ENV: ${ENV}
      VERSION: ${VERSION}
      CI: ${CI}
      BACKEND_PORT: ${BACKEND_PORT}
      BACKEND_URL: ${BACKEND_URL}
      FRONTEND_PORT: ${FRONTEND_PORT}
      FRONTEND_URL: ${FRONTEND_URL}
      MKDOCS_PORT: ${MKDOCS_PORT}
      REDIS_PORT: ${REDIS_PORT}
      DOCS_URL: ${DOCS_URL}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_SECRET: ${GITHUB_SECRET}
      GITHUB_APP: ${GITHUB_APP}
      GITHUB_APP_ID: ${GITHUB_APP_ID}
      GITHUB_PRIVATE_KEY: ${GITHUB_PRIVATE_KEY}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_SECRET: ${GOOGLE_SECRET}
      GITLAB_CLIENT_ID: ${GITLAB_CLIENT_ID}
      GITLAB_SECRET: ${GITLAB_SECRET}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DEFAULT_POSTGRES_URI: ${DEFAULT_POSTGRES_URI}
      INFODENGUE_POSTGRES_URI: ${INFODENGUE_POSTGRES_URI}
      SENTRY_DSN: ${SENTRY_DSN}
      DEFAULT_FROM_EMAIL: ${DEFAULT_FROM_EMAIL}
      EMAIL_BACKEND: ${EMAIL_BACKEND}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
      EMAIL_USE_TLS: ${EMAIL_USE_TLS}
      BACKEND_HOST_DATA_PATH: ${BACKEND_HOST_DATA_PATH}
      BACKEND_CONTAINER_DATA_PATH: ${BACKEND_CONTAINER_DATA_PATH}
      EPISCANNER_HOST_DATA_DIR: ${EPISCANNER_HOST_DATA_DIR}
      BACKUP_DIR_HOST: ${BACKUP_DIR_HOST}
      MOSQLIENT_API_URL: ${MOSQLIENT_API_URL}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      YOUTUBE_API_KEY: ${YOUTUBE_API_KEY}
      EPIDBOT_API_KEY: ${EPIDBOT_API_KEY}
    build:
      context: .
      dockerfile: containers/mosqlimate/Dockerfile
      args:
        - UID=${HOST_UID}
        - GID=${HOST_GID}
        - BACKEND_CONTAINER_DATA_PATH=${BACKEND_CONTAINER_DATA_PATH}
    ports:
      - ${WORKER_PORT}:${WORKER_PORT}
    user: "mosqlimate:mosqlimate"
    volumes:
      - /opt/services/Mosqlimate/storage/django:/opt/services/storage/django
      - /Storage/backups/mosqlimate:/opt/backups
    command: celery -A mosqlimate worker -l INFO -E -B --scheduler django_celery_beat.schedulers:DatabaseScheduler
    healthcheck:
      test: ["CMD-SHELL", 'celery --app mosqlimate.celeryapp.app status']
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - default
      - infodengue

  postgres:
    hostname: mosqlimate-${VERSION}-postgres
    restart: unless-stopped
    build:
      context: .
      dockerfile: containers/postgres/Dockerfile
      args:
        - UID=${POSTGRES_HOST_UID}
        - GID=${POSTGRES_HOST_GID}
        - environment=${ENV}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    user: "${POSTGRES_HOST_UID}:${POSTGRES_HOST_GID}"
    volumes:
      - ./containers/postgres/scripts:/docker-entrypoint-initdb.d/
      - /Storage/mosqlimateV2_data/psql:/etc/postgresql/
      - /Storage/mosqlimateV2_data/psql/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p ${POSTGRES_PORT} -U ${POSTGRES_USER}"]
      interval: 60s
      timeout: 5s
      retries: 10
    command: ["-p", "${POSTGRES_PORT}", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    networks:
      default:
        aliases:
          - mosqlimate-${VERSION}-postgres

  documentation:
    hostname: mosqlimate-${VERSION}-docs
    restart: unless-stopped
    build:
      context: .
      dockerfile: containers/mkdocs/Dockerfile
    environment:
      DOCS_URL: ${DOCS_URL}
      BACKEND_URL: ${BACKEND_URL}
    ports:
      - ${MKDOCS_PORT}:8000
    stdin_open: true
    tty: true
    entrypoint: ["/entrypoint.sh"]
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - default

  broker:
    platform: linux/amd64
    image: redis:alpine
    hostname: mosqlimate-${VERSION}-redis
    restart: unless-stopped
    command: redis-server --port ${REDIS_PORT}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "${REDIS_PORT}", "ping"]
      interval: 60s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - redis:/data
    networks:
      - default

volumes:
  redis:

networks:
  infodengue:
    name: ${INFODENGUE_NETWORK_NAME:-infodengue-prod_infodengue}
    external: true
