# Generated by Django 4.2.21 on 2025-05-27 19:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0002_centroidtest_delete_citytest_delete_statetest"),
    ]

    operations = [
        migrations.CreateModel(
            name="PolygonTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                (
                    "area",
                    django.contrib.gis.db.models.fields.PolygonField(
                        srid=4326
                    ),
                ),
            ],
        ),
    ]
