'use client';

import { useState } from "react";

function EndpointOneLayout() {
  return (
    <div>
      <h2 className="text-lg font-semibold mb-4">Municipality Data</h2>
      <p className="opacity-80">
        This endpoint provides municipality-level temperature and population data.
      </p>
      {/* custom layout for endpoint 1 */}
      <div className="mt-4 grid grid-cols-2 gap-4">
        <div className="border rounded-md p-4">Example Chart</div>
        <div className="border rounded-md p-4">Parameter Config</div>
      </div>
    </div>
  );
}

function EndpointTwoLayout() {
  return (
    <div>
      <h2 className="text-lg font-semibold mb-4">State Data</h2>
      <p className="opacity-80">
        Displays aggregated information for all states.
      </p>
      {/* custom layout for endpoint 2 */}
      <div className="mt-4 flex gap-4">
        <div className="flex-1 border rounded-md p-4">Map</div>
        <div className="flex-1 border rounded-md p-4">Statistics</div>
      </div>
    </div>
  );
}

function EndpointThreeLayout() {
  return (
    <div>
      <h2 className="text-lg font-semibold mb-4">Predictions</h2>
      <p className="opacity-80">
        Forecasts generated by trained models.
      </p>
      {/* custom layout for endpoint 3 */}
      <div className="mt-4 border rounded-md p-4">Prediction Viewer</div>
    </div>
  );
}

export default function DatastorePage() {
  const [selected, setSelected] = useState<number | null>(null);

  const renderContent = () => {
    switch (selected) {
      case 0:
        return <EndpointOneLayout />;
      case 1:
        return <EndpointTwoLayout />;
      case 2:
        return <EndpointThreeLayout />;
      default:
        return (
          <>
            <h2 className="text-lg font-semibold mb-4">Endpoint Details</h2>
            <p className="text-[var(--color-text)] opacity-80">
              Select an endpoint above to view its specifications.
            </p>
          </>
        );
    }
  };

  return (
    <section className="p-8 flex flex-col gap-8">
      <div className="w-full">
        <div className="overflow-x-auto flex gap-4 pb-2">
          {["Endpoint 1", "Endpoint 2", "Endpoint 3"].map((label, i) => (
            <div
              key={i}
              onClick={() => setSelected(i)}
              className={`min-w-[200px] h-32 rounded-md flex items-center justify-center cursor-pointer border transition-colors ${selected === i
                ? "bg-[var(--color-accent)] text-white"
                : "bg-[var(--color-border)] hover:bg-[var(--color-accent)] hover:text-white"
                }`}
            >
              {label}
            </div>
          ))}
        </div>
      </div>

      <div className="flex-1 bg-[var(--color-bg)] border border-[var(--color-border)] rounded-md p-6">
        {renderContent()}
      </div>
    </section>
  );
}
