version: '3.8'

services:
  django:
    ports:
      - ${DJANGO_PORT}:${DJANGO_PORT}
    volumes:
      - ${DJANGO_HOST_DATA_PATH}:${DJANGO_CONTAINER_DATA_PATH}
    command: python -m gunicorn -w 4 -b 0.0.0.0:${DJANGO_PORT} mosqlimate.asgi:application -k uvicorn.workers.UvicornWorker
