services:
  django:
    ports:
      - ${DJANGO_PORT}:${DJANGO_PORT}
    volumes:
      - ../backend/:/opt/services/mosqlimate
      - django_data:/opt/services/storage
    networks:
      - infodengue-dev_infodengue
    command: python manage.py runserver 0.0.0.0:8042

  worker:
    networks:
      - infodengue-dev_infodengue

volumes:
  django_data:

networks:
  infodengue-dev_infodengue:
    external: true
