services:
  frontend:
    environment:
        NODE_ENV: development
        WATCHPACK_POLLING: "true"
    volumes:
      - ../frontend/:/app
      - frontend_data:/app/node_modules
    command: npm run dev

  backend:
    volumes:
      - ../backend/:/opt/services/mosqlimate
      - backend_data:/opt/services/storage
    networks:
      - infodengue
    command: python manage.py runserver 0.0.0.0:8042

  worker:
    networks:
      - infodengue

volumes:
  backend_data:
  frontend_data:

networks:
  infodengue:
    name: infodengue-dev_infodengue
    external: true
