services:
  frontend:
    environment:
        NODE_ENV: production

  backend:
    volumes:
      - ${BACKEND_HOST_DATA_PATH}:${BACKEND_CONTAINER_DATA_PATH}
    networks:
      - infodengue-prod_infodengue

  worker:
    networks:
      - infodengue-prod_infodengue

networks:
  infodengue-prod_infodengue:
    external: true
