services:
  django:
    ports:
      - ${DJANGO_PORT}:${DJANGO_PORT}
    volumes:
      - ../src/:/opt/services/mosqlimate
      - django_data:/opt/services/storage
    networks:
      - infodengue-dev_infodengue
    command: watchmedo auto-restart --patterns="*.py" --recursive -- daphne -b 0.0.0.0 -p 8042 mosqlimate.asgi:application

  worker:
    networks:
      - infodengue-dev_infodengue

volumes:
  django_data:

networks:
  infodengue-dev_infodengue:
    external: true
