services:
  frontend:
    environment:
        NODE_ENV: production

  backend:
    volumes:
      - ${BACKEND_HOST_DATA_PATH}:${BACKEND_CONTAINER_DATA_PATH}
    networks:
      - infodengue

  worker:
    networks:
      - infodengue

networks:
  infodengue:
    name: infodengue-prod_infodengue
    external: true
