services:
  frontend:
    command: npm build
    networks:
      - infodengue-prod_infodengue

  backend:
    command: python -m gunicorn -w 4 -b 0.0.0.0:${BACKEND_PORT} backend.asgi:application -k uvicorn.workers.UvicornWorker
    networks:
      - infodengue-prod_infodengue

  worker:
    networks:
      - infodengue-prod_infodengue

networks:
  infodengue-prod_infodengue:
    external: true
