version: '3.8'

services:
  django:
    expose:
      - ${DJANGO_PORT}
    volumes:
      - ${DJANGO_ROOT_DATA_PATH}:${DJANGO_CONTAINER_DATA_PATH}

  nginx:
    hostname: nginx
    restart: unless-stopped
    build:
      context: ..
      dockerfile: containers/nginx/Dockerfile
      args:
        - CERTBOT_DOMAIN=${CERTBOT_DOMAIN}
    ports:
      - 18042:80
      - 28042:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - letsencrypt:/etc/letsencrypt
      - ${DJANGO_ROOT_DATA_PATH}/static:/var/www/certbot
    depends_on:
      - django

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - letsencrypt:/etc/letsencrypt
      - ${DJANGO_ROOT_DATA_PATH}/static:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email ${CERTBOT_EMAIL} -d ${CERTBOT_DOMAIN} --agree-tos
    depends_on:
      - nginx

volumes:
  letsencrypt:
