version: '3.8'

services:
  django:
    ports:
      - ${DJANGO_PORT}:${DJANGO_PORT}
    volumes:
      - ${DJANGO_HOST_DATA_PATH}:${DJANGO_CONTAINER_DATA_PATH}

  documentation:
    hostname: docs
    restart: unless-stopped
    build:
      context: ..
      dockerfile: containers/mkdocs/Dockerfile
    env_file:
      - ../.env
    ports:
      - ${MKDOCS_PORT}:8000
    volumes:
      - ../mkdocs:/root
    stdin_open: true
    tty: true
    command:
      - "serve"
      - "--dev-addr=0.0.0.0:8000"
      - "--config-file"
      - "./mkdocs.yml"
