version: '3.8'

services:
  django:
    expose:
      - ${DJANGO_PORT}
    volumes:
      - ${DJANGO_HOST_DATA_PATH}:${DJANGO_CONTAINER_DATA_PATH}

  nginx:
    hostname: nginx
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    environment:
      - CERTBOT_PRODUCTION_URL=https://${CERTBOT_DOMAIN}
      - CERTBOT_EMAIL=${CERTBOT_EMAIL}
    env_file:
      - ./nginx/nginx-certbot.env
    ports:
      - 18042:80
      - 28042:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/user_conf.d
      - letsencrypt:/etc/letsencrypt
    depends_on:
      - django

volumes:
  letsencrypt:
