services:
  frontend:
    environment:
        FRONTEND_ENV: dev

  backend:
    ports:
      - ${BACKEND_PORT}:8042
    volumes:
      - ../backend/:/opt/services/mosqlimate
      - backend_data:/opt/services/storage
    networks:
      - infodengue-dev_infodengue
    command: python manage.py runserver 0.0.0.0:8042

  worker:
    networks:
      - infodengue-dev_infodengue

volumes:
  backend_data:

networks:
  infodengue-dev_infodengue:
    external: true
