services:
  frontend:
    build:
      context: ..
      dockerfile: containers/frontend/Dockerfile
      target: deps
    environment:
        NODE_ENV: development
        WATCHPACK_POLLING: "true"
    volumes:
      - ../frontend/:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev

  backend:
    volumes:
      - ../backend/:/opt/services/mosqlimate
      - backend_data:/opt/services/storage
    networks:
      - infodengue
      - default
    command: python manage.py runserver 0.0.0.0:8042

  worker:
    networks:
      - infodengue
      - default

volumes:
  backend_data:

networks:
  infodengue:
    name: infodengue-dev_infodengue
    external: true
