# Generated by Django 4.2.14 on 2024-07-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("datastore", "0004_dengueglobal"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sprint202425Schema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_column="date")),
                ("year", models.BigIntegerField(db_column="year")),
                ("epiweek", models.BigIntegerField(db_column="epiweek")),
                ("casos", models.BigIntegerField(db_column="casos")),
                ("geocode", models.BigIntegerField(db_column="geocode")),
                ("regional", models.CharField(db_column="regional")),
                (
                    "regional_geocode",
                    models.IntegerField(db_column="regional_geocode"),
                ),
                (
                    "macroregional",
                    models.IntegerField(db_column="macroregional"),
                ),
                (
                    "macroregional_geocode",
                    models.IntegerField(db_column="macroregional_geocode"),
                ),
                ("uf", models.CharField(db_column="uf")),
                ("train_1", models.BooleanField(db_column="train_1")),
                ("train_2", models.BooleanField(db_column="train_2")),
                ("target_1", models.BooleanField(db_column="target_1")),
                ("target_2", models.BooleanField(db_column="target_2")),
            ],
            options={
                "db_table": "sprint202425",
                "managed": False,
            },
        ),
    ]
