# Generated by Django 4.2.18 on 2025-02-03 11:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("datastore", "0006_sprint202425_delete_sprint202425schema"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="copernicusbrasil",
            table="copernicus_bra",
        ),
    ]
