# Generated by Django 4.2.23 on 2025-12-17 13:33

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("datastore", "0008_municipio_delete_dengueglobal"),
    ]
    operations = [
        TrigramExtension(),
    ]
