# Generated by Django 4.2.23 on 2025-12-17 13:50

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("datastore", "0009_trigram_extension"),
    ]

    operations = [
        migrations.CreateModel(
            name="ICD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "system",
                    models.CharField(
                        choices=[("ICD-10", "ICD-10"), ("ICD-11", "ICD-11")],
                        max_length=10,
                    ),
                ),
                ("version", models.CharField(max_length=50)),
            ],
            options={
                "unique_together": {("system", "version")},
            },
        ),
        migrations.CreateModel(
            name="Disease",
            fields=[
                (
                    "code",
                    models.CharField(
                        max_length=20, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "icd",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diseases",
                        to="datastore.icd",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disease",
                "verbose_name_plural": "Diseases",
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["name"],
                        name="idx_disease_name_gin",
                        opclasses=["gin_trgm_ops"],
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["description"],
                        name="idx_disease_desc_gin",
                        opclasses=["gin_trgm_ops"],
                    ),
                ],
                "unique_together": {("icd", "code")},
            },
        ),
    ]
