# Generated by Django 4.2.23 on 2025-12-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datastore", "0010_icd_disease"),
    ]

    operations = [
        migrations.AddField(
            model_name="icd",
            name="release_date",
            field=models.DateField(null=True),
        ),
    ]
