# Generated by Django 4.2.23 on 2026-01-05 13:56

from django.db import migrations, transaction


def add_dv(geocode: str) -> str | None:
    if not geocode or not str(geocode).isdigit():
        return None

    miscalculated = {
        "2201911": "2201919",
        "2201986": "2201988",
        "2202257": "2202251",
        "2611531": "2611533",
        "3117835": "3117836",
        "3152139": "3152131",
        "4305876": "4305871",
        "5203963": "5203962",
        "5203930": "5203939",
    }

    if len(str(geocode)) == 7:
        return miscalculated.get(str(geocode), geocode)

    if len(str(geocode)) == 6:
        weight = [1, 2, 1, 2, 1, 2]
        total = sum(
            sum(divmod(int(d) * w, 10)) for d, w in zip(str(geocode), weight)
        )
        dv = 0 if total % 10 == 0 else 10 - (total % 10)
        code = str(geocode) + str(dv)
        return miscalculated.get(code, code)

    return None


def populate_brazil(apps, schema_editor):
    import os
    import duckdb

    Adm0 = apps.get_model("datastore", "Adm0")
    Adm1 = apps.get_model("datastore", "Adm1")
    Adm2 = apps.get_model("datastore", "Adm2")

    bra, _ = Adm0.objects.get_or_create(
        geocode="BRA", defaults={"name": "Brasil"}
    )

    db = duckdb.connect(
        os.path.join(os.path.dirname(__file__), "fixtures/BRA.duckdb"),
        read_only=True,
    )

    cities = []

    for (
        adm1_code,
        adm1_name,
        state_code,
        state_name,
        state_uf,
        hmacro_code,
        hmacro_name,
        hregion_code,
        hregion_name,
        city_code,
        city_name,
    ) in db.execute("SELECT * FROM BRA").fetchall():
        state, _ = Adm1.objects.get_or_create(
            geocode=state_code,
            country=bra,
            defaults={"name": state_name},
        )

        cities.append(
            Adm2(
                geocode=add_dv(city_code),
                name=city_name,
                adm1=state,
            )
        )

    chunk_size = 500
    for i in range(0, len(cities), chunk_size):
        with transaction.atomic():
            Adm2.objects.bulk_create(cities[i : i + chunk_size])


def delete_brazil(apps, schema_editor):
    Adm0 = apps.get_model("datastore", "Adm0")
    Adm1 = apps.get_model("datastore", "Adm1")
    Adm2 = apps.get_model("datastore", "Adm2")

    Adm2.objects.all().delete()
    Adm1.objects.all().delete()
    Adm0.objects.filter(isocode="BRA").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("datastore", "0012_adm0_adm1_adm2_adm3"),
    ]

    operations = [migrations.RunPython(populate_brazil, delete_brazil)]
