# Generated by Django 4.2.23 on 2026-01-25 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("datastore", "0013_populate_brazil_adms"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Sprint202425",
        ),
    ]
