# Generated by Django 4.2.23 on 2026-05-08 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("datastore", "0014_delete_sprint202425"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContaOvos",
            fields=[
                (
                    "counting_id",
                    models.BigIntegerField(
                        primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("date", models.DateField()),
                ("date_collect", models.DateField()),
                ("eggs", models.PositiveIntegerField()),
                (
                    "latitude",
                    models.DecimalField(decimal_places=9, max_digits=12),
                ),
                (
                    "longitude",
                    models.DecimalField(decimal_places=9, max_digits=12),
                ),
                ("ovitrap_id", models.CharField(max_length=50)),
                ("ovitrap_website_id", models.IntegerField()),
                ("time", models.DateTimeField()),
                ("week", models.PositiveSmallIntegerField()),
                ("year", models.PositiveSmallIntegerField()),
                (
                    "adm2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="datastore.adm2",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ovitrap Counting",
                "verbose_name_plural": "Ovitrap Countings",
                "ordering": ["-date"],
            },
        ),
    ]
