# Generated by Django 4.2.23 on 2026-05-08 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datastore", "0015_contaovos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contaovos",
            name="latitude",
            field=models.DecimalField(decimal_places=10, max_digits=15),
        ),
        migrations.AlterField(
            model_name="contaovos",
            name="longitude",
            field=models.DecimalField(decimal_places=10, max_digits=15),
        ),
    ]
