# Generated by Django 4.2.30 on 2026-06-19 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "datastore",
            "0016_alter_contaovos_latitude_alter_contaovos_longitude",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="VegetationIndexMetric",
            fields=[
                ("date", models.DateField(primary_key=True, serialize=False)),
                ("geocode", models.IntegerField()),
                ("collection", models.CharField(max_length=255)),
                ("attribute", models.CharField(max_length=50)),
                ("mean", models.FloatField(blank=True, null=True)),
                ("std", models.FloatField(blank=True, null=True)),
                ("median", models.FloatField(blank=True, null=True)),
                ("q25", models.FloatField(blank=True, null=True)),
                ("q75", models.FloatField(blank=True, null=True)),
                ("min", models.FloatField(blank=True, null=True)),
                ("max", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "vegetation_index_metrics",
                "managed": False,
            },
        ),
    ]
