# Generated by Django 4.2.30 on 2026-07-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datastore", "0017_vegetationindexmetric"),
    ]

    operations = [
        migrations.CreateModel(
            name="EpiscannerSirParams",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cid10", models.CharField(max_length=10)),
                ("year", models.IntegerField()),
                (
                    "ep_ini",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("ep_pw", models.CharField(max_length=20)),
                (
                    "ep_end",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("ep_dur", models.IntegerField(blank=True, null=True)),
                ("peak_week", models.FloatField()),
                ("beta", models.FloatField()),
                ("gamma", models.FloatField()),
                ("r0", models.FloatField()),
                ("total_cases", models.FloatField()),
                ("alpha", models.FloatField()),
                ("sum_res", models.FloatField()),
                ("t_ini", models.IntegerField(blank=True, null=True)),
                ("t_end", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": '"episcanner"."sir_params"',
                "managed": False,
            },
        ),
    ]
