# Generated by Django 4.2.30 on 2026-08-11 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datastore", "0018_episcannersirparams"),
    ]

    operations = [
        migrations.CreateModel(
            name="CopernicusBrasilPrecipFixed",
            fields=[
                (
                    "date",
                    models.DateField(
                        db_column="date", primary_key=True, serialize=False
                    ),
                ),
                ("geocode", models.BigIntegerField(db_column="geocode")),
                ("precip_min", models.FloatField(db_column="precip_min")),
                ("precip_med", models.FloatField(db_column="precip_med")),
                ("precip_max", models.FloatField(db_column="precip_max")),
                ("precip_tot", models.FloatField(db_column="precip_tot")),
            ],
            options={
                "db_table": "copernicus_bra_precip_tot_fixed",
                "managed": False,
            },
        ),
    ]
