# Generated by Django 4.2.3 on 2023-08-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="institution",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="model",
            name="description",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="model",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="model",
            name="repository",
            field=models.URLField(max_length=150),
        ),
        migrations.AlterField(
            model_name="model",
            name="type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="prediction",
            name="commit",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="prediction",
            name="description",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
