# Generated by Django 4.2.3 on 2023-08-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0006_auto_20230829_1437"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImplementationLanguage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(max_length=100)),
                (
                    "svg_path",
                    models.FilePathField(
                        null=True,
                        path="/home/bida/Projetos/Mosqlimate/Data-platform/src/staticfiles/img/plangs",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Implementation Language",
                "verbose_name_plural": "Implementation Languages",
            },
        ),
    ]
