# Generated by Django 4.2.3 on 2023-08-29 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0009_alter_model_implementation_language_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="implementationlanguage",
            name="language",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
