# Generated by Django 4.2.3 on 2023-08-29 17:59

from django.db import migrations, models


def create_initial_objects(apps, schema_editor):
    ImplementationLanguage = apps.get_model(
        "registry", "ImplementationLanguage"
    )

    languages_and_icons = [
        ("Python", "python.svg"),
        ("C++", "cplusplus.svg"),
        ("CoffeeScript", "coffeescript.svg"),
        ("C#", "csharp.svg"),
        ("C", "c.svg"),
        (".NET", "dot-net.svg"),
        ("Erlang", "erlang.svg"),
        ("Go", "go.svg"),
        ("Haskell", "haskell.svg"),
        ("JavaScript", "javascript.svg"),
        ("Java", "java.svg"),
        ("Kotlin", "kotlin.svg"),
        ("Lua", "lua.svg"),
        ("R", "r.svg"),
        ("Ruby", "ruby.svg"),
        ("Rust", "rust.svg"),
        ("Zig", "zig.svg"),
    ]

    for language, icon in languages_and_icons:
        ImplementationLanguage.objects.get_or_create(
            language=language, svg_path=icon
        )


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0010_alter_implementationlanguage_language"),
    ]

    operations = [migrations.RunPython(create_initial_objects)]
