# Generated by Django 4.2.5 on 2023-11-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0015_model_periodicity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="model",
            name="periodicity",
        ),
        migrations.AddField(
            model_name="model",
            name="time_resolution",
            field=models.CharField(
                choices=[
                    ("day", "Day"),
                    ("week", "Week"),
                    ("month", "Month"),
                    ("year", "Year"),
                ],
                null=True,
            ),
        ),
    ]
