# Generated by Django 4.2.7 on 2023-11-13 05:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0016_remove_model_periodicity_model_time_resolution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="implementationlanguage",
            name="svg_path",
            field=models.FilePathField(
                match=".svg$",
                null=True,
                path="/opt/services/mosqlimate/staticfiles/img/plangs",
            ),
        ),
    ]
