# Generated by Django 4.2.7 on 2023-11-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0019_prediction_adm_2_geocode_alter_model_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="implementationlanguage",
            name="svg_path",
            field=models.FilePathField(
                match=".svg$",
                null=True,
                path="/opt/services/mosqlimate/staticfiles/img/plangs",
            ),
        ),
    ]
