# Generated by Django 4.2.13 on 2024-06-25 12:22

from django.db import migrations, models


def populate_default_tags(apps, schema_editor):
    Tag = apps.get_model("registry", "Tag")
    Tag.objects.get_or_create(name="Spatial", color="#4500db")
    Tag.objects.get_or_create(name="Temporal", color="#00d824")
    Tag.objects.get_or_create(name="Quantitative", color="#ddc018")
    Tag.objects.get_or_create(name="Qualitative", color="#cb00d6")
    Tag.objects.get_or_create(name="Daily", color="#d3005b")
    Tag.objects.get_or_create(name="Weekly", color="#b700d3")
    Tag.objects.get_or_create(name="Monthly", color="#9400d3")
    Tag.objects.get_or_create(name="Yearly", color="#cb00d6")
    Tag.objects.get_or_create(name="ADM 1", color="#adadff")
    Tag.objects.get_or_create(name="ADM 2", color="#b5ecff")
    Tag.objects.get_or_create(name="ADM 3", color="#99ffd7")
    Tag.objects.get_or_create(name="ADM 0", color="#ebff93")
    Tag.objects.get_or_create(name="Dengue", color="#ff003b")
    Tag.objects.get_or_create(name="Zika", color="#aa00ff")
    Tag.objects.get_or_create(name="Chikungunya", color="#00bfff")


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0030_alter_model_tags"),
    ]

    operations = [
        migrations.RunPython(populate_default_tags),
    ]
