# Generated by Django 4.2.13 on 2024-06-25 12:22

from django.db import migrations, models


def populate_default_tags(apps, schema_editor):
    Tag = apps.get_model("registry", "Tag")
    Tag.objects.get_or_create(name="Spatio-Temporal", color=Tag.random_rgb())
    Tag.objects.get_or_create(name="Spatial", color=Tag.random_rgb())
    Tag.objects.get_or_create(name="Temporal", color=Tag.random_rgb())
    Tag.objects.get_or_create(name="Quantitative", color=Tag.random_rgb())
    Tag.objects.get_or_create(name="Categorical", color=Tag.random_rgb())
    Tag.objects.get_or_create(name="Daily", color=Tag.random_rgb())
    Tag.objects.get_or_create(name="Weekly", color=Tag.random_rgb())
    Tag.objects.get_or_create(name="Monthly", color=Tag.random_rgb())
    Tag.objects.get_or_create(name="Yearly", color=Tag.random_rgb())
    Tag.objects.get_or_create(name="ADM 1", color=Tag.random_rgb())
    Tag.objects.get_or_create(name="ADM 2", color=Tag.random_rgb())
    Tag.objects.get_or_create(name="ADM 3", color=Tag.random_rgb())
    Tag.objects.get_or_create(name="ADM 0", color=Tag.random_rgb())
    Tag.objects.get_or_create(name="Dengue", color=Tag.random_rgb())
    Tag.objects.get_or_create(name="Zika", color=Tag.random_rgb())
    Tag.objects.get_or_create(name="Chikungunya", color=Tag.random_rgb())
    Tag.objects.get_or_create(name="Sprint2425", color=Tag.random_rgb())
    Tag.objects.get_or_create(name="Python", color=Tag.random_rgb())
    Tag.objects.get_or_create(name="C++", color=Tag.random_rgb())
    Tag.objects.get_or_create(name="CoffeeScript", color=Tag.random_rgb())
    Tag.objects.get_or_create(name="C#", color=Tag.random_rgb())
    Tag.objects.get_or_create(name="C", color=Tag.random_rgb())
    Tag.objects.get_or_create(name=".NET", color=Tag.random_rgb())
    Tag.objects.get_or_create(name="Erlang", color=Tag.random_rgb())
    Tag.objects.get_or_create(name="Go", color=Tag.random_rgb())
    Tag.objects.get_or_create(name="Haskell", color=Tag.random_rgb())
    Tag.objects.get_or_create(name="JavaScript", color=Tag.random_rgb())
    Tag.objects.get_or_create(name="Java", color=Tag.random_rgb())
    Tag.objects.get_or_create(name="Kotlin", color=Tag.random_rgb())
    Tag.objects.get_or_create(name="Lua", color=Tag.random_rgb())
    Tag.objects.get_or_create(name="R", color=Tag.random_rgb())
    Tag.objects.get_or_create(name="Ruby", color=Tag.random_rgb())
    Tag.objects.get_or_create(name="Rust", color=Tag.random_rgb())
    Tag.objects.get_or_create(name="Zig", color=Tag.random_rgb())


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0030_alter_model_tags"),
    ]

    operations = [
        migrations.RunPython(populate_default_tags),
    ]
