# Generated by Django 4.2.13 on 2024-07-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0032_alter_tag_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="model",
            name="sprint",
            field=models.BooleanField(
                default=False, help_text="Model created to Sprint 2024/25"
            ),
        ),
    ]
