# Generated by Django 4.2.14 on 2024-07-23 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0033_model_sprint"),
    ]

    operations = [
        migrations.CreateModel(
            name="PredictionDataRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dates", models.DateField()),
                ("preds", models.FloatField()),
                ("lower", models.FloatField()),
                ("upper", models.FloatField()),
                ("adm_0", models.CharField(max_length=3, null=True)),
                ("adm_1", models.CharField(max_length=2, null=True)),
                ("adm_2", models.IntegerField(null=True)),
                ("adm_3", models.IntegerField(null=True)),
                (
                    "predict",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data",
                        to="registry.prediction",
                    ),
                ),
            ],
        ),
    ]
