# Generated by Django 4.2.15 on 2024-08-23 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0038_rename_dates_predictiondatarow_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="predictiondatarow",
            name="predict",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data",
                to="registry.prediction",
            ),
        ),
    ]
