# Generated by Django 4.2.17 on 2025-01-15 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0042_alter_prediction_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="group",
            field=models.CharField(null=True, unique=True),
        ),
    ]
