# Generated by Django 4.2.20 on 2025-03-21 20:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0050_predictiondatarow_lower_50_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="predictiondatarow",
            name="adm_0",
        ),
        migrations.RemoveField(
            model_name="predictiondatarow",
            name="adm_1",
        ),
        migrations.RemoveField(
            model_name="predictiondatarow",
            name="adm_2",
        ),
        migrations.RemoveField(
            model_name="predictiondatarow",
            name="adm_3",
        ),
    ]
