# Generated by Django 4.2.21 on 2025-05-16 12:39

from django.db import migrations


def populate_adm_fields(apps, schema_editor):
    Prediction = apps.get_model("registry", "Prediction")
    City = apps.get_model("vis", "City")
    State = apps.get_model("vis", "State")

    for prediction in Prediction.objects.all():
        try:
            if prediction.model.ADM_level == 1:
                state = State.objects.filter(
                    geocode=prediction.adm_1_geocode
                ).first()
                prediction.adm_1 = state

            if prediction.model.ADM_level == 2:
                city = City.objects.filter(
                    geocode=prediction.adm_2_geocode
                ).first()
                prediction.adm_2 = city

            prediction.save()
        except Exception as e:
            print(e)
            pass


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0055_alter_prediction_adm_1_alter_prediction_adm_2"),
    ]

    operations = [
        migrations.RunPython(populate_adm_fields),
    ]
