# Generated by Django 4.2.21 on 2025-05-22 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0056_auto_20250516_1000"),
    ]

    operations = [
        migrations.RenameField(
            model_name="model",
            old_name="ADM_level",
            new_name="adm_level",
        ),
    ]
