# Generated by Django 4.2.23 on 2025-07-18 18:07

from django.db import migrations, models


def include_octave(apps, schema_editor):
    ImplementationLanguage = apps.get_model(
        "registry", "ImplementationLanguage"
    )

    ImplementationLanguage.objects.get_or_create(
        language="Octave", svg_path="octave.svg"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0057_rename_adm_level_model_adm_level"),
    ]

    operations = [migrations.RunPython(include_octave)]
