# Generated by Django 4.2.3 on 2023-09-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("datastore", "0003_historicoalertachik_historicoalertazika"),
    ]

    operations = [
        migrations.CreateModel(
            name="DengueGlobal",
            fields=[
                (
                    "geocodigo",
                    models.IntegerField(
                        db_column="geocodigo", primary_key=True, serialize=False
                    ),
                ),
                ("nome", models.CharField(db_column="nome")),
                ("uf", models.CharField(db_column="uf")),
            ],
            options={
                "db_table": '"Municipio"',
                "managed": False,
            },
        ),
    ]
