# Generated by Django 4.2.20 on 2025-03-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("datastore", "0007_alter_copernicusbrasil_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Municipio",
            fields=[
                (
                    "geocodigo",
                    models.IntegerField(
                        db_column="geocodigo",
                        db_index=True,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(db_column="nome")),
                ("uf", models.CharField(db_column="uf")),
                (
                    "regional_code",
                    models.IntegerField(db_column="id_regional"),
                ),
            ],
            options={
                "db_table": '"Municipio"',
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="DengueGlobal",
        ),
    ]
