# Generated by Django 4.2.21 on 2025-05-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datastore", "0008_municipio_delete_dengueglobal"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricoAlertaChikPartial",
            fields=[
                (
                    "data_iniSE",
                    models.DateField(db_column="data_iniSE", db_index=True),
                ),
                ("SE", models.IntegerField(db_column="SE")),
                ("casos_est", models.FloatField(db_column="casos_est")),
                (
                    "casos_est_min",
                    models.IntegerField(db_column="casos_est_min"),
                ),
                (
                    "casos_est_max",
                    models.IntegerField(db_column="casos_est_max"),
                ),
                ("casos", models.IntegerField(db_column="casos")),
                (
                    "municipio_geocodigo",
                    models.IntegerField(db_column="municipio_geocodigo"),
                ),
                ("p_rt1", models.FloatField(db_column="p_rt1")),
                ("p_inc100k", models.FloatField(db_column="p_inc100k")),
                ("nivel", models.SmallIntegerField(db_column="nivel")),
                (
                    "id",
                    models.BigAutoField(
                        db_column="id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "versao_modelo",
                    models.CharField(db_column="versao_modelo", max_length=40),
                ),
                (
                    "municipio_nome",
                    models.CharField(
                        db_column="municipio_nome", max_length=128
                    ),
                ),
                (
                    "Rt",
                    models.FloatField(db_column="Rt", default=None, null=True),
                ),
                (
                    "pop",
                    models.DecimalField(
                        db_column="pop", decimal_places=0, max_digits=10
                    ),
                ),
                ("receptivo", models.SmallIntegerField(db_column="receptivo")),
                (
                    "transmissao",
                    models.SmallIntegerField(db_column="transmissao"),
                ),
                ("nivel_inc", models.SmallIntegerField(db_column="nivel_inc")),
                ("casprov", models.IntegerField(db_column="casprov")),
            ],
            options={
                "db_table": '"Historico_alerta_chik"',
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="HistoricoAlertaPartial",
            fields=[
                (
                    "data_iniSE",
                    models.DateField(db_column="data_iniSE", db_index=True),
                ),
                ("SE", models.IntegerField(db_column="SE")),
                ("casos_est", models.FloatField(db_column="casos_est")),
                (
                    "casos_est_min",
                    models.IntegerField(db_column="casos_est_min"),
                ),
                (
                    "casos_est_max",
                    models.IntegerField(db_column="casos_est_max"),
                ),
                ("casos", models.IntegerField(db_column="casos")),
                (
                    "municipio_geocodigo",
                    models.IntegerField(db_column="municipio_geocodigo"),
                ),
                ("p_rt1", models.FloatField(db_column="p_rt1")),
                ("p_inc100k", models.FloatField(db_column="p_inc100k")),
                ("nivel", models.SmallIntegerField(db_column="nivel")),
                (
                    "id",
                    models.BigAutoField(
                        db_column="id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "versao_modelo",
                    models.CharField(db_column="versao_modelo", max_length=40),
                ),
                (
                    "municipio_nome",
                    models.CharField(
                        db_column="municipio_nome", max_length=128
                    ),
                ),
                (
                    "Rt",
                    models.FloatField(db_column="Rt", default=None, null=True),
                ),
                (
                    "pop",
                    models.DecimalField(
                        db_column="pop", decimal_places=0, max_digits=10
                    ),
                ),
                ("receptivo", models.SmallIntegerField(db_column="receptivo")),
                (
                    "transmissao",
                    models.SmallIntegerField(db_column="transmissao"),
                ),
                ("nivel_inc", models.SmallIntegerField(db_column="nivel_inc")),
                ("casprov", models.IntegerField(db_column="casprov")),
            ],
            options={
                "db_table": '"Historico_alerta"',
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="HistoricoAlertaZikaPartial",
            fields=[
                (
                    "data_iniSE",
                    models.DateField(db_column="data_iniSE", db_index=True),
                ),
                ("SE", models.IntegerField(db_column="SE")),
                ("casos_est", models.FloatField(db_column="casos_est")),
                (
                    "casos_est_min",
                    models.IntegerField(db_column="casos_est_min"),
                ),
                (
                    "casos_est_max",
                    models.IntegerField(db_column="casos_est_max"),
                ),
                ("casos", models.IntegerField(db_column="casos")),
                (
                    "municipio_geocodigo",
                    models.IntegerField(db_column="municipio_geocodigo"),
                ),
                ("p_rt1", models.FloatField(db_column="p_rt1")),
                ("p_inc100k", models.FloatField(db_column="p_inc100k")),
                ("nivel", models.SmallIntegerField(db_column="nivel")),
                (
                    "id",
                    models.BigAutoField(
                        db_column="id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "versao_modelo",
                    models.CharField(db_column="versao_modelo", max_length=40),
                ),
                (
                    "municipio_nome",
                    models.CharField(
                        db_column="municipio_nome", max_length=128
                    ),
                ),
                (
                    "Rt",
                    models.FloatField(db_column="Rt", default=None, null=True),
                ),
                (
                    "pop",
                    models.DecimalField(
                        db_column="pop", decimal_places=0, max_digits=10
                    ),
                ),
                ("receptivo", models.SmallIntegerField(db_column="receptivo")),
                (
                    "transmissao",
                    models.SmallIntegerField(db_column="transmissao"),
                ),
                ("nivel_inc", models.SmallIntegerField(db_column="nivel_inc")),
                ("casprov", models.IntegerField(db_column="casprov")),
            ],
            options={
                "db_table": '"Historico_alerta_zika"',
                "managed": False,
            },
        ),
    ]
