# Generated by Django 4.2.23 on 2026-03-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="language",
            field=models.CharField(default="en", max_length=10),
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="session_key",
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
