# Generated by Django 4.2.5 on 2024-01-03 19:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vis", "0003_alter_totalcases100khab_total_cases"),
    ]

    operations = [
        migrations.AlterField(
            model_name="totalcases",
            name="year",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1980),
                    django.core.validators.MaxValueValidator(2024),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="totalcases100khab",
            name="year",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1980),
                    django.core.validators.MaxValueValidator(2024),
                ]
            ),
        ),
    ]
