# Generated by Django 4.2.5 on 2024-03-06 17:27

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("vis", "0004_alter_totalcases_year_alter_totalcases100khab_year"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeoCity",
            fields=[
                (
                    "geocode",
                    models.CharField(
                        max_length=7,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        srid=4326
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GeoMacroregion",
            fields=[
                (
                    "geocode",
                    models.CharField(
                        max_length=1,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        srid=4326
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GeoMacroSaude",
            fields=[
                (
                    "geocode",
                    models.CharField(
                        max_length=4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        srid=4326
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GeoMesoregion",
            fields=[
                (
                    "geocode",
                    models.CharField(
                        max_length=4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        srid=4326
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GeoMicroregion",
            fields=[
                (
                    "geocode",
                    models.CharField(
                        max_length=5,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        srid=4326
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GeoState",
            fields=[
                (
                    "geocode",
                    models.CharField(
                        max_length=2,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        srid=4326
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Macroregion",
            fields=[
                (
                    "geocode",
                    models.CharField(
                        max_length=1,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField()),
                (
                    "geo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="vis.geomacroregion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "geocode",
                    models.CharField(
                        max_length=2,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField()),
                ("uf", models.CharField(max_length=2)),
                (
                    "geo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="vis.geostate",
                    ),
                ),
                (
                    "macroregion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="vis.macroregion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResultsProbLSTM",
            fields=[
                (
                    "date",
                    models.DateField(
                        db_column="date", primary_key=True, serialize=False
                    ),
                ),
                ("lower_2_5", models.FloatField()),
                ("lower_25", models.FloatField()),
                ("forecast", models.FloatField()),
                ("upper_75", models.FloatField()),
                ("upper_97_5", models.FloatField()),
                ("prob_high", models.FloatField()),
                ("prob_low", models.FloatField()),
                ("HT", models.FloatField()),
                ("LT", models.FloatField()),
                ("HTinc", models.FloatField()),
                ("LTinc", models.FloatField()),
                (
                    "macroregion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="vis.geomacrosaude",
                    ),
                ),
            ],
            options={
                "db_table": "results_prob_lstm",
            },
        ),
        migrations.CreateModel(
            name="Microregion",
            fields=[
                (
                    "geocode",
                    models.CharField(
                        max_length=5,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField()),
                (
                    "geo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="vis.geomicroregion",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="vis.state",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mesoregion",
            fields=[
                (
                    "geocode",
                    models.CharField(
                        max_length=4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField()),
                (
                    "geo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="vis.geomesoregion",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="vis.state",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "geocode",
                    models.CharField(
                        max_length=7,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField()),
                (
                    "geo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="vis.geostate",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="vis.state",
                    ),
                ),
            ],
        ),
    ]
