# Generated by Django 4.2.13 on 2024-05-21 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "registry",
            "0027_prediction_adm_0_geocode_prediction_adm_1_geocode_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("vis", "0012_resultsprobforecast_disease"),
    ]

    operations = [
        migrations.CreateModel(
            name="RPFMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveConstraint(
            model_name="resultsprobforecast",
            name="results_prob_forecast_unique",
        ),
        migrations.AddConstraint(
            model_name="resultsprobforecast",
            constraint=models.UniqueConstraint(
                fields=("disease", "date", "geocode"),
                name="results_prob_forecast_unique",
            ),
        ),
        migrations.AddField(
            model_name="rpfmap",
            name="forecast",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="vis.resultsprobforecast",
            ),
        ),
        migrations.AddField(
            model_name="rpfmap",
            name="model",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                to="registry.model",
            ),
        ),
        migrations.AddField(
            model_name="rpfmap",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
