# Generated by Django 4.2.13 on 2024-05-22 06:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vis", "0013_rpfmap_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rpfmap",
            name="description",
        ),
    ]
