# Generated by Django 4.2.17 on 2025-01-15 14:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vis", "0014_alter_resultsprobforecast_disease_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="totalcases",
            name="year",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1980),
                    django.core.validators.MaxValueValidator(2025),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="totalcases100khab",
            name="year",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1980),
                    django.core.validators.MaxValueValidator(2025),
                ]
            ),
        ),
    ]
