services:
  frontend:
    command: npm run dev
    networks:
      - infodengue-dev_infodengue

  backend:
    # command: python -m gunicorn -w 1 -b 0.0.0.0:${BACKEND_PORT} backend.mosqlimate.asgi:application -k uvicorn.workers.UvicornWorker --reload
    command: python backend/manage.py runserver ${BACKEND_PORT} --reload
    networks:
      - infodengue-dev_infodengue

  worker:
    networks:
      - infodengue-dev_infodengue

networks:
  infodengue-dev_infodengue:
    external: true
