services:
  frontend:
    networks:
      - infodengue-dev_infodengue

  backend:
    command: poetry run gunicorn -w 1 -b 0.0.0.0:${BACKEND_PORT} -k uvicorn.workers.UvicornWorker mosqlimate.asgi:application --chdir backend --limit-request-line 8188 --log-file - --reload
    networks:
      - infodengue-dev_infodengue

  worker:
    networks:
      - infodengue-dev_infodengue

networks:
  infodengue-dev_infodengue:
    external: true
