# Generated by Django 4.2.3 on 2023-09-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("datastore", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CopernicusBrasil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_column="date")),
                ("geocodigo", models.BigIntegerField(db_column="geocodigo")),
                ("temp_min", models.FloatField(db_column="temp_min")),
                ("temp_med", models.FloatField(db_column="temp_med")),
                ("temp_max", models.FloatField(db_column="temp_max")),
                ("precip_min", models.FloatField(db_column="precip_min")),
                ("precip_med", models.FloatField(db_column="precip_med")),
                ("precip_max", models.FloatField(db_column="precip_max")),
                ("precip_tot", models.FloatField(db_column="precip_tot")),
                ("pressao_min", models.FloatField(db_column="pressao_min")),
                ("pressao_med", models.FloatField(db_column="pressao_med")),
                ("pressao_max", models.FloatField(db_column="pressao_max")),
                ("umid_min", models.FloatField(db_column="umid_min")),
                ("umid_med", models.FloatField(db_column="umid_med")),
                ("umid_max", models.FloatField(db_column="umid_max")),
            ],
            options={
                "db_table": "copernicus_brasil",
                "managed": False,
            },
        ),
    ]
