# Generated by Django 4.2.3 on 2023-08-17 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "registry",
            "0003_alter_author_institution_alter_model_description_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="model",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="registry.author",
            ),
        ),
    ]
