# Generated by Django 4.2.3 on 2023-08-29 17:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0005_alter_author_user_alter_model_author"),
    ]

    operations = []
