# Generated by Django 4.2.3 on 2023-08-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0007_implementationlanguage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="implementationlanguage",
            name="svg_path",
            field=models.FilePathField(
                match=".svg$",
                null=True,
                path="/home/bida/Projetos/Mosqlimate/Data-platform/src/staticfiles/img/plangs",
            ),
        ),
    ]
