# Generated by Django 4.2.3 on 2023-08-29 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0008_alter_implementationlanguage_svg_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="model",
            name="implementation_language",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="registry.implementationlanguage",
            ),
        ),
        migrations.AlterField(
            model_name="model",
            name="repository",
            field=models.CharField(max_length=100),
        ),
    ]
