# Generated by Django 4.2.5 on 2023-11-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0017_alter_implementationlanguage_svg_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="model",
            name="disease",
            field=models.CharField(
                choices=[
                    ("chikungunya", "Chikungunya"),
                    ("dengue", "Dengue"),
                    ("zika", "Zika"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="implementationlanguage",
            name="svg_path",
            field=models.FilePathField(
                match=".svg$",
                null=True,
                path="/home/bida/Projetos/Mosqlimate/Data-platform/src/staticfiles/img/plangs",
            ),
        ),
    ]
