# Generated by Django 4.2.5 on 2023-12-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0021_prediction_compatible_predictions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="implementationlanguage",
            name="svg_path",
            field=models.FilePathField(
                match=".svg$",
                null=True,
                path="/opt/services/Mosqlimate/Data-platform/src/staticfiles/img/plangs",
            ),
        ),
    ]
