# Generated by Django 4.2.5 on 2023-12-29 21:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "registry",
            "0023_prediction_visualizable_alter_model_categorical_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="model",
            name="temporal",
            field=models.BooleanField(default=None, null=True),
        ),
    ]
