# Generated by Django 4.2.5 on 2023-12-29 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0024_model_temporal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="model",
            name="categorical",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="model",
            name="spatial",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="model",
            name="temporal",
            field=models.BooleanField(default=None, null=True),
        ),
    ]
