# Generated by Django 4.2.5 on 2024-05-08 02:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0022_alter_implementationlanguage_svg_path"),
        (
            "registry",
            "0025_alter_model_categorical_alter_model_spatial_and_more",
        ),
    ]

    operations = []
