# Generated by Django 4.2.13 on 2024-05-24 07:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0028_tag_model_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="active",
        ),
    ]
