# Generated by Django 4.2.13 on 2024-06-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0029_remove_tag_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="model",
            name="tags",
            field=models.ManyToManyField(
                default=[], related_name="tags", to="registry.tag"
            ),
        ),
    ]
