# Generated by Django 4.2.13 on 2024-06-25 12:22

from django.db import migrations, models


def populate_default_tags(apps, schema_editor):
    from registry.models import random_rgb

    Tag = apps.get_model("registry", "Tag")
    Tag.objects.get_or_create(name="Spatio-Temporal", color=random_rgb())
    Tag.objects.get_or_create(name="Spatial", color=random_rgb())
    Tag.objects.get_or_create(name="Temporal", color=random_rgb())
    Tag.objects.get_or_create(name="Quantitative", color=random_rgb())
    Tag.objects.get_or_create(name="Categorical", color=random_rgb())
    Tag.objects.get_or_create(name="Daily", color=random_rgb())
    Tag.objects.get_or_create(name="Weekly", color=random_rgb())
    Tag.objects.get_or_create(name="Monthly", color=random_rgb())
    Tag.objects.get_or_create(name="Yearly", color=random_rgb())
    Tag.objects.get_or_create(name="ADM 1", color=random_rgb())
    Tag.objects.get_or_create(name="ADM 2", color=random_rgb())
    Tag.objects.get_or_create(name="ADM 3", color=random_rgb())
    Tag.objects.get_or_create(name="ADM 0", color=random_rgb())
    Tag.objects.get_or_create(name="Dengue", color=random_rgb())
    Tag.objects.get_or_create(name="Zika", color=random_rgb())
    Tag.objects.get_or_create(name="Chikungunya", color=random_rgb())
    Tag.objects.get_or_create(name="Sprint2425", color=random_rgb())
    Tag.objects.get_or_create(name="Python", color=random_rgb())
    Tag.objects.get_or_create(name="C++", color=random_rgb())
    Tag.objects.get_or_create(name="CoffeeScript", color=random_rgb())
    Tag.objects.get_or_create(name="C#", color=random_rgb())
    Tag.objects.get_or_create(name="C", color=random_rgb())
    Tag.objects.get_or_create(name=".NET", color=random_rgb())
    Tag.objects.get_or_create(name="Erlang", color=random_rgb())
    Tag.objects.get_or_create(name="Go", color=random_rgb())
    Tag.objects.get_or_create(name="Haskell", color=random_rgb())
    Tag.objects.get_or_create(name="JavaScript", color=random_rgb())
    Tag.objects.get_or_create(name="Java", color=random_rgb())
    Tag.objects.get_or_create(name="Kotlin", color=random_rgb())
    Tag.objects.get_or_create(name="Lua", color=random_rgb())
    Tag.objects.get_or_create(name="R", color=random_rgb())
    Tag.objects.get_or_create(name="Ruby", color=random_rgb())
    Tag.objects.get_or_create(name="Rust", color=random_rgb())
    Tag.objects.get_or_create(name="Zig", color=random_rgb())


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0030_alter_model_tags"),
    ]

    operations = [
        migrations.RunPython(populate_default_tags),
    ]
