# Generated by Django 4.2.13 on 2024-07-09 19:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0031_include_default_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="color",
            field=models.CharField(
                help_text="Color in hexadecimal format. E.g: #ffffff",
                max_length=7,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Color must be in hexadecimal format, e.g., #ffffff",
                        regex="^#[0-9A-Fa-f]{6}$",
                    )
                ],
            ),
        ),
    ]
