# Generated by Django 4.2.15 on 2024-09-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0039_alter_predictiondatarow_predict"),
    ]

    operations = [
        migrations.AlterField(
            model_name="predictiondatarow",
            name="adm_0",
            field=models.CharField(default="BRA", max_length=3),
        ),
    ]
