# Generated by Django 4.2.15 on 2024-10-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0040_alter_predictiondatarow_adm_0"),
    ]

    operations = [
        migrations.AlterField(
            model_name="implementationlanguage",
            name="svg_path",
            field=models.FilePathField(
                match=".svg$",
                null=True,
                path="/home/bida/Projetos/Mosqlimate/Data-platform/backend/../frontend/staticfiles/img/plangs",
            ),
        ),
    ]
