# Generated by Django 4.2.18 on 2025-01-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0044_prediction_tags_alter_model_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="group",
            field=models.CharField(null=True),
        ),
    ]
