# Generated by Django 4.2.20 on 2025-03-20 21:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0048_remove_prediction_metadata"),
    ]

    operations = [
        migrations.RenameField(
            model_name="predictiondatarow",
            old_name="lower",
            new_name="lower_90",
        ),
        migrations.RenameField(
            model_name="predictiondatarow",
            old_name="upper",
            new_name="upper_90",
        ),
    ]
