# Generated by Django 4.2.20 on 2025-03-20 22:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0049_rename_lower_predictiondatarow_lower_90_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="predictiondatarow",
            name="lower_50",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="predictiondatarow",
            name="lower_80",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="predictiondatarow",
            name="lower_95",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="predictiondatarow",
            name="upper_50",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="predictiondatarow",
            name="upper_80",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="predictiondatarow",
            name="upper_95",
            field=models.FloatField(null=True),
        ),
    ]
