# Generated by Django 4.2.25 on 2025-10-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0061_prediction_wis"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
