# Generated by Django 4.2.23 on 2025-11-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0062_tag_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="implementationlanguage",
            name="svg_path",
            field=models.FilePathField(
                match=".svg$",
                null=True,
                path="/home/bida/Projetos/Mosqlimate/Data-platform/backend/staticfiles/img/plangs",
            ),
        ),
    ]
