# Generated by Django 4.2.23 on 2025-12-18 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0064_organization_repository_repositorymodel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repositorymodel",
            name="repository",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="model",
                to="registry.repository",
            ),
        ),
    ]
