# Generated by Django 4.2.23 on 2025-12-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0065_alter_repositorymodel_repository"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="model_avatars/"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="avatar_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
