# Generated by Django 4.2.23 on 2025-12-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0066_organization_avatar_organization_avatar_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.RemoveField(
            model_name="repositorymodel",
            name="sprint",
        ),
    ]
