# Generated by Django 4.2.23 on 2025-12-26 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0067_sprint_remove_repositorymodel_sprint"),
    ]

    operations = [
        migrations.AddField(
            model_name="repositorymodel",
            name="sprint",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="registry.sprint",
            ),
        ),
    ]
