# Generated by Django 4.2.23 on 2026-01-02 00:25

from django.db import migrations


def create_2024_and_25_sprints(apps, schema_editor):
    Sprint = apps.get_model("registry", "Sprint")

    Sprint.objects.get_or_create(
        year=2025,
        defaults={
            "start_date": "2025-05-15",
            "end_date": "2025-09-23",
        },
    )

    Sprint.objects.get_or_create(
        year=2024,
        defaults={
            "start_date": "2024-06-20",
            "end_date": "2024-08-16",
        },
    )


def remove_sprints(apps, schema_editor):
    Sprint = apps.get_model("registry", "Sprint")
    Sprint.objects.filter(year__in=[2024, 2025]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0068_repositorymodel_sprint"),
    ]

    operations = [
        migrations.RunPython(create_2024_and_25_sprints, remove_sprints),
    ]
