# Generated by Django 4.2.23 on 2026-01-02 00:42

from django.db import migrations
from urllib.parse import urlparse


def migrate_legacy_models(apps, schema_editor):
    OldModel = apps.get_model("registry", "Model")
    RepositoryModel = apps.get_model("registry", "RepositoryModel")
    Repository = apps.get_model("registry", "Repository")
    ICD = apps.get_model("datastore", "ICD")
    Disease = apps.get_model("datastore", "Disease")
    Sprint = apps.get_model("registry", "Sprint")
    User = apps.get_model("users", "CustomUser")

    cid10 = ICD.objects.get(system="ICD-10", version="2010")
    diseases = {}
    for dis, cid in [
        ("dengue", "A90"),
        ("zika", "A92.5"),
        ("chikungunya", "A92.0"),
    ]:
        obj = Disease.objects.get(icd=cid10, code=cid)
        diseases[dis] = obj

    sprint_2024 = Sprint.objects.filter(year=2024).first()
    sprint_2025 = Sprint.objects.filter(year=2025).first()

    for old in OldModel.objects.all():
        repo_string = old.repository.strip()
        owner_username = None
        repo_name = repo_string

        parsed = urlparse(repo_string)
        path = parsed.path.strip("/")
        parts = path.split("/")

        if len(parts) >= 2:
            owner_username = parts[0]
            repo_name = parts[1].replace(".git", "")
        elif len(parts) == 1 and "/" in repo_string:
            manual_parts = repo_string.split("/")
            if len(manual_parts) >= 2:
                owner_username = manual_parts[0]
                repo_name = manual_parts[1].replace(".git", "")

        if owner_username == "Mosqlimate-project":
            owner_username = "eduardocorrearaujo"

        owner_user = User.objects.filter(
            username__iexact=owner_username
        ).first()

        repository, _ = Repository.objects.get_or_create(
            repo_id=repo_string,  # NOTE: doing this to not hit gh api on
            #                        migrations, but it should be an int
            defaults={
                "name": repo_name,
                "provider": "github",
                "owner": owner_user,
                "organization": None,
                "active": True,
            },
        )

        is_spatial = old.spatial or False
        is_temporal = old.temporal or False
        is_categorical = old.categorical or False

        category = "quantitative"

        if is_spatial and is_temporal:
            category = (
                "spatio_temporal_categorical"
                if is_categorical
                else "spatio_temporal_quantitative"
            )
        elif is_spatial:
            category = (
                "spatial_categorical"
                if is_categorical
                else "spatial_quantitative"
            )
        elif is_categorical:
            category = "categorical"
        elif is_temporal:
            category = "quantitative"

        sprint = None
        if old.sprint:
            year = old.created.year
            if year == 2024:
                sprint = sprint_2024
            elif year >= 2025:
                sprint = sprint_2025
            else:
                sprint = sprint_2024

        RepositoryModel.objects.update_or_create(
            repository=repository,
            defaults={
                "disease": diseases.get(old.disease, None),
                "description": old.description,
                "category": category,
                "adm_level": old.adm_level or 0,
                "time_resolution": old.time_resolution or "week",
                "sprint": sprint,
            },
        )


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0069_create_former_sprints"),
        ("datastore", "0010_icd_disease"),
    ]

    operations = [
        migrations.RunPython(migrate_legacy_models),
    ]
