# Generated by Django 4.2.23 on 2026-01-02 00:42

from django.db import migrations


def migrate_legacy_models(apps, schema_editor):
    OldModel = apps.get_model("registry", "Model")
    RepositoryModel = apps.get_model("registry", "RepositoryModel")
    Repository = apps.get_model("registry", "Repository")
    ICD = apps.get_model("datastore", "ICD")
    Disease = apps.get_model("datastore", "Disease")
    Sprint = apps.get_model("registry", "Sprint")
    User = apps.get_model("users", "CustomUser")

    cid10 = ICD.objects.get(system="ICD-10", version="2010")
    diseases = {}
    for dis, cid in [
        ("dengue", "A90"),
        ("zika", "A92.5"),
        ("chikungunya", "A92.0"),
    ]:
        obj = Disease.objects.get(icd=cid10, code=cid)
        diseases[dis] = obj

    sprint_2024 = Sprint.objects.filter(year=2024).first()
    sprint_2025 = Sprint.objects.filter(year=2025).first()

    for old in OldModel.objects.all():
        repo_string = old.repository.strip()
        owner_username = None
        repo_name = repo_string

        if "/" in repo_string:
            parts = repo_string.strip("/").split("/")
            owner_username = parts[-2]
            repo_name = parts[-1]

        owner_user = User.objects.filter(
            username__iexact=owner_username
        ).first()

        repository, _ = Repository.objects.get_or_create(
            repo_id=repo_string,  # NOTE: doing this to not hit gh api on
            #                        migrations, but it should be an int
            defaults={
                "name": repo_name,
                "provider": "github",
                "owner": owner_user,
                "organization": None,
                "active": True,
            },
        )

        is_spatial = old.spatial or False
        is_temporal = old.temporal or False
        is_categorical = old.categorical or False

        new_category = "quantitative"

        if is_spatial and is_temporal:
            new_category = (
                "spatio_temporal_categorical"
                if is_categorical
                else "spatio_temporal_quantitative"
            )
        elif is_spatial:
            new_category = (
                "spatial_categorical"
                if is_categorical
                else "spatial_quantitative"
            )
        elif is_categorical:
            new_category = "categorical"
        elif is_temporal:
            new_category = "quantitative"

        sprint = None
        if old.sprint:
            year = old.created.year
            if year == 2024:
                sprint = sprint_2024
            elif year >= 2025:
                sprint = sprint_2025
            else:
                sprint = sprint_2024

        RepositoryModel.objects.create(
            repository=repository,
            disease=diseases.get(old.disease, None),
            description=old.description,
            category=new_category,
            adm_level=old.adm_level or 0,
            time_resolution=old.time_resolution or "week",
            sprint=sprint,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0069_create_former_sprints"),
        ("datastore", "0010_icd_disease"),
    ]

    operations = [
        migrations.RunPython(migrate_legacy_models),
    ]
