# Generated by Django 4.2.23 on 2026-01-03 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("datastore", "0012_adm0_adm1_adm2_adm3"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("registry", "0070_create_repositories_from_former_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("commit", models.CharField(max_length=100)),
                (
                    "description",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                ("predict_date", models.DateField()),
                ("published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "adm0",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="datastore.adm0",
                    ),
                ),
                (
                    "adm1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="datastore.adm1",
                    ),
                ),
                (
                    "adm2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="datastore.adm2",
                    ),
                ),
                (
                    "adm3",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="datastore.adm3",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="registry.model",
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
        ),
        migrations.AlterField(
            model_name="sprint",
            name="end_date",
            field=models.DateField(help_text="End submission date"),
        ),
        migrations.AlterField(
            model_name="sprint",
            name="start_date",
            field=models.DateField(help_text="Start submission date"),
        ),
        migrations.CreateModel(
            name="QuantitativePrediction",
            fields=[
                (
                    "modelprediction_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="registry.modelprediction",
                    ),
                ),
                ("mae_score", models.FloatField(default=None, null=True)),
                ("mse_score", models.FloatField(default=None, null=True)),
                ("crps_score", models.FloatField(default=None, null=True)),
                ("log_score", models.FloatField(default=None, null=True)),
                ("interval_score", models.FloatField(default=None, null=True)),
                ("wis_score", models.FloatField(default=None, null=True)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("registry.modelprediction",),
        ),
    ]
