# Generated by Django 4.2.23 on 2026-01-05 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0071_modelprediction_alter_sprint_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelprediction",
            name="model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="registry.repositorymodel",
            ),
        ),
        migrations.CreateModel(
            name="QuantitativePredictionRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("pred", models.FloatField()),
                ("lower_95", models.FloatField(null=True)),
                ("lower_90", models.FloatField()),
                ("lower_80", models.FloatField(null=True)),
                ("lower_50", models.FloatField(null=True)),
                ("upper_50", models.FloatField(null=True)),
                ("upper_80", models.FloatField(null=True)),
                ("upper_90", models.FloatField()),
                ("upper_95", models.FloatField(null=True)),
                (
                    "prediction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data",
                        to="registry.quantitativeprediction",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
                "indexes": [
                    models.Index(
                        fields=["prediction", "date"],
                        name="registry_qu_predict_870ab9_idx",
                    )
                ],
            },
        ),
    ]
