# Generated by Django 4.2.23 on 2026-01-16 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0073_migrate_predictions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="modelprediction",
            options={},
        ),
        migrations.AlterModelOptions(
            name="quantitativeprediction",
            options={},
        ),
        migrations.RemoveField(
            model_name="modelprediction",
            name="polymorphic_ctype",
        ),
        migrations.AlterField(
            model_name="modelprediction",
            name="model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="predicts",
                to="registry.repositorymodel",
            ),
        ),
    ]
