# Generated by Django 4.2.23 on 2026-01-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0074_alter_modelprediction_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Creation timestamp"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, help_text="Last update timestamp"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The full title of the publication.",
                        max_length=500,
                    ),
                ),
                (
                    "authors_list",
                    models.TextField(
                        help_text="Full list of authors as they appear in the citation (e.g., 'Silva, J.; Doe, J.')."
                    ),
                ),
                (
                    "publication_type",
                    models.CharField(
                        choices=[
                            ("conference", "Conference Proceeding"),
                            ("journal", "Journal Article"),
                            ("preprint", "Preprint"),
                            ("thesis", "Thesis/Dissertation"),
                            ("report", "Technical Report"),
                            ("other", "Other"),
                        ],
                        default="journal",
                        max_length=20,
                    ),
                ),
                ("year", models.IntegerField(help_text="Year of publication")),
                (
                    "date",
                    models.DateField(
                        blank=True,
                        help_text="Specific publication date if available (e.g. for preprints).",
                        null=True,
                    ),
                ),
                (
                    "venue",
                    models.CharField(
                        blank=True,
                        help_text="Name of the Journal, Conference, or Institution (for theses).",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "volume",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "issue",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "pages",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "doi",
                    models.CharField(
                        blank=True,
                        help_text="Digital Object Identifier (e.g., 10.1098/rsos.241261)",
                        max_length=100,
                        null=True,
                        verbose_name="DOI",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="Link to the paper or PDF.",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "related_models",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Models discussed or used in this publication.",
                        related_name="publications",
                        to="registry.repositorymodel",
                    ),
                ),
                (
                    "related_sprints",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Sprints associated with this publication.",
                        related_name="publications",
                        to="registry.sprint",
                    ),
                ),
            ],
            options={
                "verbose_name": "Publication",
                "verbose_name_plural": "Publications",
                "ordering": ["-year", "-date", "title"],
            },
        ),
    ]
