# Generated by Django 4.2.23 on 2026-02-09 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0075_publication"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="model",
            name="author",
        ),
        migrations.RemoveField(
            model_name="model",
            name="implementation_language",
        ),
        migrations.RemoveField(
            model_name="model",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="prediction",
            name="adm_1",
        ),
        migrations.RemoveField(
            model_name="prediction",
            name="adm_2",
        ),
        migrations.RemoveField(
            model_name="prediction",
            name="model",
        ),
        migrations.RemoveField(
            model_name="prediction",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="predictiondatarow",
            name="predict",
        ),
        migrations.DeleteModel(
            name="Author",
        ),
        migrations.DeleteModel(
            name="ImplementationLanguage",
        ),
        migrations.DeleteModel(
            name="Model",
        ),
        migrations.DeleteModel(
            name="Prediction",
        ),
        migrations.DeleteModel(
            name="PredictionDataRow",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
