# Generated by Django 4.2.23 on 2026-02-09 16:43

from django.db import migrations, models


def set_case_definition(apps, schema_editor):
    ModelPrediction = apps.get_model("registry", "ModelPrediction")
    ModelPrediction.objects.filter(model__sprint__isnull=False).update(
        case_definition="probable"
    )
    ModelPrediction.objects.filter(model__sprint__isnull=True).update(
        case_definition="reported"
    )


def reverse_case_definition(apps, schema_editor):
    ModelPrediction = apps.get_model("registry", "ModelPrediction")
    ModelPrediction.objects.all().update(case_definition="probable")


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0076_remove_model_author_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelprediction",
            name="case_definition",
            field=models.CharField(
                choices=[("reported", "Reported"), ("probable", "Probable")],
                default="reported",
                max_length=20,
            ),
        ),
        migrations.RunPython(set_case_definition, reverse_case_definition),
    ]
