# Generated by Django 4.2.23 on 2026-02-11 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0077_modelprediction_case_definition"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="modelprediction",
            name="predict_date",
        ),
    ]
