# Generated by Django 4.2.23 on 2026-03-27 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0079_move_disease_adm_level_to_prediction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationmembership",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="registry.organization",
            ),
        ),
    ]
