# Generated by Django 4.2.23 on 2025-11-11 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_oauthaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="avatars/"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="avatar_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="homepage",
            field=models.URLField(max_length=255, null=True),
        ),
    ]
