# Generated by Django 4.2.23 on 2025-12-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_migrate_former_allauth_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oauthaccount",
            name="provider",
            field=models.CharField(
                choices=[
                    ("google", "Google"),
                    ("github", "GitHub"),
                    ("gitlab", "GitLab"),
                ],
                max_length=20,
            ),
        ),
    ]
