# Generated by Django 4.2.23 on 2025-12-04 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_oauthaccount_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oauthaccount",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="oauth_accounts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
