# Generated by Django 4.2.23 on 2025-12-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_oauthaccount_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="oauthaccount",
            name="access_token",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="oauthaccount",
            name="refresh_token",
            field=models.TextField(blank=True, null=True),
        ),
    ]
