# Generated by Django 4.2.23 on 2025-12-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_oauthaccount_access_token_oauthaccount_refresh_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="oauthaccount",
            name="refresh_token",
        ),
        migrations.AddField(
            model_name="oauthaccount",
            name="installation_access_token",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="oauthaccount",
            name="installation_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="oauthaccount",
            name="installation_metadata",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="oauthaccount",
            name="installation_token_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
