# Generated by Django 4.2.23 on 2025-12-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_remove_oauthaccount_refresh_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="oauthaccount",
            name="access_token_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="oauthaccount",
            name="refresh_token",
            field=models.TextField(blank=True, null=True),
        ),
    ]
