# Generated by Django 4.2.30 on 2026-06-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_oauthaccount_access_token_expires_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="created_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
