# Generated by Django 4.2.30 on 2026-06-22 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_customuser_created_ip_customuser_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="rate_limit",
            field=models.CharField(default="10/s", max_length=20),
        ),
    ]
