# Generated by Django 4.2.11 on 2024-05-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vis", "0011_geomacrosaude_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="resultsprobforecast",
            name="disease",
            field=models.CharField(
                choices=[
                    ("dengue", "Dengue"),
                    ("chik", "Chigungunya"),
                    ("zika", "Zika"),
                ],
                default="dengue",
            ),
        ),
    ]
